---
kind: pipeline
type: docker
name: build-go1.22

steps:
  - name: build-go1.22-alpine3.20
    image: golang:1.22-alpine3.20
    environment:
      CGO_ENABLED: "0"
      GOOS: linux
      GOARCH: amd64
    commands:
      - apk update
      - apk add --no-cache git
      - go build -v ./cmd/go-away
---
kind: pipeline
type: docker
name: build-go1.24

steps:
  - name: build-go1.24-alpine3.21
    image: golang:1.24-alpine3.21
    environment:
      CGO_ENABLED: "0"
      GOOS: linux
      GOARCH: amd64
    commands:
      - apk update
      - apk add --no-cache git
      - go build -v ./cmd/go-away
...

