# Configuration file
# Parameters that exist both on config and cmdline will have cmdline as preference

bind:
  #address: ":8080"
  #network: "tcp"
  #socket-mode": "0770"

  # Enable PROXY mode on this listener, to allow passing origin info. Default false
  #proxy: true

  # Enable passthrough mode, which will allow traffic onto the backends while rules load. Default false
  #passthrough: true

  # Enable TLS on this listener and obtain certificates via an ACME directory URL, or letsencrypt
  #tls-acme-autocert: "letsencrypt"

  # Enable TLS on this listener and obtain certificates via a certificate and key file on disk
  # Only set one of tls-acme-autocert or tls-certificate+tls-key
  #tls-certificate: ""
  #tls-key: ""

# Bind the Go debug port
#bind-debug: ":6060"

# Bind the Prometheus metrics onto /metrics path on this port
#bind-metrics: ":9090"

# These links will be shown on the presented challenge or error pages
links:
  #- name: Privacy
  #  url: "/privacy.html"

  #- name: Contact
  #  url: "mailto:admin@example.com"

  #- name: Donations
  #  url: "https://donations.example.com/abcd"

# HTML Template to use for challenge or error pages
# External templates can be included by providing a disk path
# Bundled templates:
#  anubis: An Anubis-like template with no configuration parameters. Supports Logo.
#  forgejo: Looks like native Forgejo. Includes logos and resources from your instance. Supports Theme, Logo.
#
#challenge-template: "anubis"

# Allows overriding specific settings set on templates. Key-Values will be passed to templates as-is
challenge-template-overrides:
  # Set template theme if supported
  #Theme: "forgejo-auto"
  # Set logo on template if supported
  #Logo: "/my/custom/logo/path.png"

# Change the default HTTP code sent when serving challenges.
#challenge-http-code: 418

# Advanced backend configuration
# Backends setup via cmdline will be added here
backends:
  # Example HTTP backend and setting client ip header
  #"git.example.com":
  #  url: "http://forgejo:3000"
  #  ip-header: "X-Client-Ip"

  # Example HTTP backend matching a non-standard port in Host
  # Standard ports are 80 and 443. Others will be sent in Host by browsers
  #"git.example.com:8080":
  #  url: "http://forgejo:3000"
  #  ip-header: "X-Client-Ip"


  # Example HTTPS backend with host/SNI override, HTTP/2 and no certificate verification
  #"ssl.example.com":
  #  url: "https://127.0.0.1:8443"
  #  host: ssl.example.com
  #  http2-enabled: true
  #  tls-skip-verify: true

  # Example HTTPS transparent backend with host/SNI override, HTTP/2, and subdirectory
  #"ssl.example.com":
  #  url: "https://ssl.example.com/subdirectory/"
  #  host: ssl.example.com
  #  http2-enabled: true
  #  ip-header: "-"
  #  transparent: true

# List of strings you can replace to alter the presentation on challenge/error templates
# Can use other languages.
# Note raw HTML is allowed, be careful with it.
# Default strings exist in code, uncomment any to set it
strings:
  #title_challenge: "Checking you are not a bot"
  #title_error: "Oh no!"
  #noscript_warning: "<p>Sadly, you may need to enable JavaScript to get past this challenge. This is required because AI companies have changed the social contract around how website hosting works.</p>"
  #details_title: "Why am I seeing this?"
  #details_text: >
  #  <p>
  #  You are seeing this because the administrator of this website has set up <a href="https://git.gammaspectra.live/git/go-away">go-away</a>
  #  to protect the server against the scourge of <a href="https://thelibre.news/foss-infrastructure-is-under-attack-by-ai-companies/">AI companies aggressively scraping websites</a>.
  #  </p>
  #  <p>
  #  Mass scraping can and does cause downtime for the websites, which makes their resources inaccessible for everyone.
  #  </p>
  #  <p>
  #  Please note that some challenges requires the use of modern JavaScript features and some plugins may disable these.
  #  Disable such plugins for this domain (for example, JShelter) if you encounter any issues.
  #  </p>

  #details_contact_admin_with_request_id: "If you have any issues contact the site administrator and provide the following Request Id"

  #button_refresh_page: "Refresh page"

  #status_loading_challenge: "Loading challenge"
  #status_starting_challenge: "Starting challenge"
  #status_loading: "Loading..."
  #status_calculating: "Calculating..."
  #status_challenge_success: "Challenge success!"
  #status_challenge_done_took: "Done! Took"
  #status_error: "Error:"